<?php
declare(strict_types=1);

// The Builder's own workbench strings in German - see en_US.php, which names
// the parts. Capitalised Du, as everywhere.
return [

	'[[/_admin/builder/label/nav]]'						=> 'Builder',

	'[[/_admin/builder/label/new]]'						=> 'Neues Template',
	'[[/_admin/builder/label/create]]'				=> 'Anlegen',
	'[[/_admin/builder/label/name]]'					=> 'Name',
	'[[/_admin/builder/label/file]]'					=> 'Datei',
	'[[/_admin/builder/label/header]]'				=> 'Kopfbereich',
	'[[/_admin/builder/label/footer]]'				=> 'Fußbereich',
	'[[/_admin/builder/label/sections]]'			=> 'Sections',
	'[[/_admin/builder/label/used-by]]'				=> 'Verwendet von',
	'[[/_admin/builder/label/none]]'					=> 'keiner',
	'[[/_admin/builder/label/open]]'					=> 'Öffnen',
	'[[/_admin/builder/label/duplicate]]'				=> 'Duplizieren',
	'[[/_admin/builder/label/copy-of]]'					=> 'Kopie von %s',
	'[[/_admin/builder/label/delete]]'					=> 'Löschen',
	'[[/_admin/builder/label/reload]]'					=> 'Neu laden',

	'[[/_admin/builder/empty/headline]]'				=> 'Noch kein Seitentemplate',
	'[[/_admin/builder/empty/lead]]'						=> 'Ein Seitentemplate ist eine page-*.tpl des Projekts. Lege hier eines an oder schreibe eines von Hand: Der Builder liest beides.',

	'[[/_admin/builder/msg/deleted]]'					=> 'Das Template ist gelöscht. Seine Textschlüssel und Bildplätze bleiben.',
	'[[/_admin/builder/confirm/delete]]'				=> 'Dieses Template löschen? Seine Textschlüssel und Bildplätze bleiben.',
	'[[/_admin/builder/confirm/delete-node]]'			=> 'Darin liegt noch etwas. Mit allem löschen, was darin ist?',
	'[[/_admin/builder/confirm/vpa-follow]]'			=> 'Die Animation des Templates hat sich geändert. Sollen die Sections, die wie das Template sind, ihr folgen? Betroffen: %s.',
	'[[/_admin/builder/confirm/vpa-yes]]'				=> 'Mitändern',
	'[[/_admin/builder/confirm/vpa-no]]'				=> 'So lassen, wie sie sind',

	'[[/_admin/builder/error/file]]'					=> 'Das ist kein Name für ein Seitentemplate: page- und danach Kleinbuchstaben, Ziffern und Bindestriche.',
	'[[/_admin/builder/error/name]]'					=> 'Ein Name ist eine Zeile von 1 bis 160 Zeichen, ohne spitze und eckige Klammern.',
	'[[/_admin/builder/error/header]]'				=> 'Das Projekt hat kein solches Kopfbereich-Template.',
	'[[/_admin/builder/error/footer]]'				=> 'Das Projekt hat kein solches Fußbereich-Template.',
	'[[/_admin/builder/error/missing]]'				=> 'Dieses Seitentemplate gibt es nicht.',
	'[[/_admin/builder/error/exists]]'					=> 'Ein Seitentemplate mit diesem Namen gibt es schon.',
	'[[/_admin/builder/error/in-use]]'					=> 'Eine Route rendert dieses Template, deshalb wird es nicht gelöscht. Ändere zuerst die Route.',
	'[[/_admin/builder/error/conflict]]'				=> 'Die Datei hat sich seit dem Laden geändert - in einem anderen Fenster oder in einem anderen Editor.',
	'[[/_admin/builder/error/invalid]]'				=> 'Das Template ist nicht gültig, und es wurde nichts geschrieben.',
	'[[/_admin/builder/error/model]]'					=> 'Es gab nichts zu speichern.',
	'[[/_admin/builder/error/key]]'						=> 'Ein Textschlüssel konnte nicht angelegt, kopiert oder verschoben werden.',
	'[[/_admin/builder/error/slot]]'						=> 'Ein Bildplatz konnte nicht angelegt oder kopiert werden.',
	'[[/_admin/builder/error/value]]'						=> 'Ein Wert enthält ein Anführungszeichen, eine eckige Klammer oder einen Zeilenumbruch, die ein Shortcode-Aufruf nicht tragen kann. Es wurde nichts geschrieben.',
	'[[/_admin/builder/error/key-exists]]'				=> 'Ein Schlüssel oder ein Bildplatz, den eine umbenannte Section oder eine Kopie anlegen würde, ist schon da. Es wurde nichts geändert.',
	'[[/_admin/builder/error/keys-in-the-way]]'			=> 'Schlüssel im Weg: %s.',
	'[[/_admin/builder/error/slots-in-the-way]]'			=> 'Bildplätze im Weg: %s.',
	'[[/_admin/builder/error/permission]]'			=> 'Dabei werden Schlüssel oder Bildplätze angelegt oder verschoben, und die Berechtigung des Panels, dem sie gehören, fehlt.',
	'[[/_admin/builder/error/write]]'					=> 'Die Datei konnte nicht geschrieben werden.',
	'[[/_admin/builder/error/load]]'						=> 'Die Seitentemplates konnten nicht geladen werden.',

	'[[/_admin/builder/reason/not-a-section]]'			=> 'Ein Block, der keine Section ist',
	'[[/_admin/builder/reason/marker-unclosed]]'		=> 'Eine HTML+-Markierung, die nie geschlossen wird',
	'[[/_admin/builder/reason/attribute-syntax]]'		=> 'Ein Tag, dessen Attribute nicht als name="wert" geschrieben sind',
	'[[/_admin/builder/reason/section-attribute]]'	=> 'Die Section hat das Attribut %s, das der Builder nicht behält',
	'[[/_admin/builder/reason/section-id]]'				=> 'Die Section hat keine Id, die ein Slug ist',
	'[[/_admin/builder/reason/duplicate-id]]'			=> 'Die Id %s gehört schon einer früheren Section',
	'[[/_admin/builder/reason/section-class]]'			=> 'Der Section fehlt die Klasse nino-section',
	'[[/_admin/builder/reason/class-token]]'				=> 'Die Klasse %s enthält Zeichen, die der Builder nicht behält',
	'[[/_admin/builder/reason/attribute-value]]'		=> 'Das Attribut %s hat einen Wert, den der Builder nicht behält',
	'[[/_admin/builder/reason/background-class]]'	=> 'Der Hintergrundblock hat %s, das der Builder nicht behält',
	'[[/_admin/builder/reason/background-image]]'	=> 'Der Hintergrundblock ist nicht genau ein Bildaufruf mit leerem Alt-Text',
	'[[/_admin/builder/reason/no-row]]'						=> 'Die Section hat keine Row',
	'[[/_admin/builder/reason/second-row]]'				=> 'Die Section hat mehr als eine Row',
	'[[/_admin/builder/reason/section-content]]'		=> 'Die Section enthält Markup neben ihrer Row',
	'[[/_admin/builder/reason/row-attribute]]'			=> 'Die Row hat das Attribut %s, das der Builder nicht behält',
	'[[/_admin/builder/reason/row-content]]'				=> 'In der Row steht etwas, das keine Col ist',
	'[[/_admin/builder/reason/no-cols]]'						=> 'Die Row hat keine Col',
	'[[/_admin/builder/reason/nested-row]]'				=> 'Eine Row in einer Row',
	'[[/_admin/builder/reason/col-attribute]]'			=> 'Die Col hat das Attribut %s, das der Builder nicht behält',
	'[[/_admin/builder/reason/col-width]]'					=> 'Der Col fehlt eine Breitenklasse für einen Viewport',
	'[[/_admin/builder/reason/col-markup]]'				=> 'In der Col steht Markup neben den Komponentenaufrufen: %s',
	'[[/_admin/builder/reason/unknown-shortcode]]'	=> 'Der Shortcode %s ist weder eine registrierte Komponente noch ein Loop',
	'[[/_admin/builder/reason/call-arguments]]'		=> 'Ein Aufruf, dessen Argumente nicht so geschrieben sind, wie der Kernel sie liest: %s',
	'[[/_admin/builder/reason/unknown-attribute]]'	=> 'Das Attribut %s gehört nicht zur Komponente',
	'[[/_admin/builder/reason/component-content]]'	=> 'Die Komponente %s nimmt keinen Inhalt',
	'[[/_admin/builder/reason/nested-call]]'				=> 'Ein Aufruf im Inhalt von %s',
	'[[/_admin/builder/reason/stack-source]]'			=> 'Ein Loop ohne den Typ, den er durchläuft',
	'[[/_admin/builder/reason/stack-neighbour]]'		=> 'Ein Loop mit weiteren Komponenten in seiner Col',
	'[[/_admin/builder/reason/stack-in-stack]]'		=> 'Ein Loop in einem Loop',
	'[[/_admin/builder/reason/stack-content]]'			=> 'Im Loop steht Markup neben den Komponentenaufrufen: %s',

	// The editor: the preview, the viewports, the bar
	'[[/_admin/builder/label/preview]]'						=> 'Vorschau',
	'[[/_admin/builder/label/viewports]]'					=> 'Viewport der Vorschau',
	'[[/_admin/builder/label/source]]'						=> 'Quelltext',
	'[[/_admin/builder/label/open-page]]'					=> 'Seite öffnen',
	'[[/_admin/builder/label/close]]'						=> 'Schließen',
	'[[/_admin/builder/label/search]]'						=> 'Templates suchen',
	'[[/_admin/builder/label/no-match]]'					=> 'Kein Template passt.',
	'[[/_admin/builder/label/not-read]]'				=> 'Der Builder liest diese Datei nicht vollständig.',
	'[[/_admin/builder/label/force]]'						=> 'Trotzdem speichern',
	'[[/_admin/builder/viewport/s]]'						=> 'Handy',
	'[[/_admin/builder/viewport/m]]'						=> 'Tablet',
	'[[/_admin/builder/viewport/l]]'						=> 'Desktop',
	'[[/_admin/builder/preview/background]]'				=> 'Ein Bild hinter der Section',
	'[[/_admin/builder/preview/hidden]]'					=> 'In diesem Viewport verborgen',

	// The frames, what they are called and the buttons on them
	'[[/_admin/builder/tree/template]]'						=> 'Template',
	'[[/_admin/builder/tree/section]]'						=> 'Section',
	'[[/_admin/builder/tree/html-block]]'					=> 'HTML+-Block',
	'[[/_admin/builder/tree/col]]'							=> 'Spalte',
	'[[/_admin/builder/tree/stack]]'						=> 'Loop',
	'[[/_admin/builder/tree/component]]'					=> 'Komponente',
	'[[/_admin/builder/tree/red-static]]'					=> 'Ein Feld eines Elements bedeutet in einer Spalte ohne Loop nichts. Wähle einen Textschlüssel oder einen festen Wert.',
	'[[/_admin/builder/tree/red-field]]'					=> 'Der Typ des Loops hat kein solches Feld. Wähle eine andere Quelle.',
	'[[/_admin/builder/tree/red-type]]'						=> 'Das Elements-Panel kennt diesen Typ nicht. Wähle einen anderen.',
	'[[/_admin/builder/menu/settings]]'						=> 'Einstellungen',
	'[[/_admin/builder/menu/template]]'						=> 'Einstellungen des Templates',
	'[[/_admin/builder/menu/edit-html]]'					=> 'Als HTML+ bearbeiten',
	'[[/_admin/builder/menu/duplicate]]'					=> 'Duplizieren',
	'[[/_admin/builder/menu/tools]]'					=> 'Werkzeuge',

	// The words of the forms
	'[[/_admin/builder/tab/general]]'						=> 'Allgemein',
	'[[/_admin/builder/tab/background]]'					=> 'Hintergrund',
	'[[/_admin/builder/tab/spacing]]'						=> 'Abstände',
	'[[/_admin/builder/tab/animation]]'						=> 'Animation',
	'[[/_admin/builder/tab/custom]]'						=> 'Eigenes',
	'[[/_admin/builder/tab/layout]]'						=> 'Layout',
	'[[/_admin/builder/tab/stack]]'							=> 'Loop',
	'[[/_admin/builder/section/title]]'						=> 'Section „%s“',
	'[[/_admin/builder/section/id]]'						=> 'Id',
	'[[/_admin/builder/section/row]]'						=> 'Zeile',
	'[[/_admin/builder/section/width]]'						=> 'Breite der Section',
	'[[/_admin/builder/section/color]]'						=> 'Farbe',
	'[[/_admin/builder/section/border]]'					=> 'Rahmen',
	'[[/_admin/builder/section/image]]'						=> 'Bild',
	'[[/_admin/builder/section/dim]]'						=> 'Bild abdunkeln',
	'[[/_admin/builder/section/image-pos]]'					=> 'Lage des Bildes',
	'[[/_admin/builder/section/cover]]'						=> 'Höhe des Covers',
	'[[/_admin/builder/section/text]]'						=> 'Textausrichtung',
	'[[/_admin/builder/section/row-align]]'					=> 'Ausrichtung der Spalten',
	'[[/_admin/builder/section/above]]'					=> 'Oben',
	'[[/_admin/builder/section/below]]'					=> 'Unten',
	'[[/_admin/builder/section/outer]]'					=> 'Außen',
	'[[/_admin/builder/section/inner]]'					=> 'Innen',
	'[[/_admin/builder/section/custom]]'					=> 'Eigene Klassen',
	'[[/_admin/builder/section/row-custom]]'				=> 'Eigene Klassen der Zeile',
	'[[/_admin/builder/section/vpa]]'						=> 'Animation',
	'[[/_admin/builder/section/vpa-effect]]'			=> 'Effekt',
	'[[/_admin/builder/section/vpa-speed]]'					=> 'Geschwindigkeit',
	'[[/_admin/builder/section/vpa-mode]]'					=> 'Läuft',
	'[[/_admin/builder/section/vpa-delay]]'					=> 'Verzögerung',
	'[[/_admin/builder/section/vpa-duration]]'				=> 'Dauer',
	'[[/_admin/builder/col/title]]'							=> 'Spalte von „%s“',
	'[[/_admin/builder/col/width]]'							=> 'Breite, %s',
	'[[/_admin/builder/col/hidden]]'						=> 'Verborgen, %s',
	'[[/_admin/builder/col/head-device]]'				=> 'Gerät',
	'[[/_admin/builder/col/head-width]]'				=> 'Breite',
	'[[/_admin/builder/col/head-hidden]]'				=> 'Verborgen',
	'[[/_admin/builder/col/stack-align]]'					=> 'Ausrichtung der Komponenten',
	'[[/_admin/builder/col/stack-gap]]'						=> 'Abstand zwischen den Komponenten',
	'[[/_admin/builder/stack/static]]'						=> 'Statisch',
	'[[/_admin/builder/stack/kind]]'						=> 'Loop',
	'[[/_admin/builder/stack/type]]'						=> 'Typ',
	'[[/_admin/builder/stack/type-hint]]'					=> 'Der Loop nimmt die Typen, die das Elements-Panel hat. Ein Typ, der fehlt, wird zuerst dort angelegt.',
	'[[/_admin/builder/stack/type-missing]]'				=> 'Das Elements-Panel hat diesen Typ nicht. Wähle einen, oder lege ihn zuerst dort an.',
	'[[/_admin/builder/stack/types-link]]'					=> 'Elementtypen',
	'[[/_admin/builder/stack/sort]]'						=> 'Sortieren nach',
	'[[/_admin/builder/stack/direction]]'					=> 'Richtung',
	'[[/_admin/builder/stack/asc]]'							=> 'Aufsteigend',
	'[[/_admin/builder/stack/desc]]'						=> 'Absteigend',
	'[[/_admin/builder/stack/limit]]'						=> 'Limit',
	'[[/_admin/builder/stack/offset]]'						=> 'Offset',
	'[[/_admin/builder/stack/query]]'						=> 'Abfrage',
	'[[/_admin/builder/stack/cells]]'						=> 'Zellbreite, %s',
	'[[/_admin/builder/stack/gap]]'							=> 'Abstand zwischen den Zellen',
	'[[/_admin/builder/stack/autoheight]]'					=> 'Zellen gleich hoch',
	'[[/_admin/builder/stack/id]]'							=> 'Id des Loops',
	'[[/_admin/builder/component/title]]'					=> 'Komponente „%s“',
	'[[/_admin/builder/component/content]]'					=> 'Inhalt',
	'[[/_admin/builder/html/title]]'						=> 'Als HTML+ bearbeiten',
	'[[/_admin/builder/html/title-new]]'					=> 'Neuer HTML+-Block',
	'[[/_admin/builder/html/apply]]'						=> 'Übernehmen',
	'[[/_admin/builder/html/source]]'						=> 'Das Markup des Blocks',
	'[[/_admin/builder/html/note]]'							=> 'Hier ist alles erlaubt, und nichts wird bereinigt. Beim Übernehmen liest der Builder den Block erneut: Liest er sich als Section, ist er von da an eine, sonst bleibt er, wie er ist.',
	'[[/_admin/builder/html/note-section]]'					=> 'Das ist das Markup, das der Builder für die Section schreibt. Beim Übernehmen liest er es erneut - eine Section, die er weiter liest, bleibt eine Section.',

	// The source of a component
	'[[/_admin/builder/source/title]]'						=> 'Quelle',
	'[[/_admin/builder/source/current]]'					=> 'Jetzt:',
	'[[/_admin/builder/source/tab-text]]'					=> 'Text',
	'[[/_admin/builder/source/tab-image]]'					=> 'Bild',
	'[[/_admin/builder/source/tab-fixed]]'					=> 'Fest',
	'[[/_admin/builder/source/key]]'						=> 'Textschlüssel',
	'[[/_admin/builder/source/field]]'						=> 'Feld des Elements',
	'[[/_admin/builder/source/search]]'						=> 'Schlüssel nach Name oder Text suchen',
	'[[/_admin/builder/source/search-slot]]'				=> 'Bildplatz suchen',
	'[[/_admin/builder/source/slot]]'						=> 'Bildplatz',
	'[[/_admin/builder/source/empty-slot]]'					=> 'noch kein Bild',
	'[[/_admin/builder/source/typed]]'						=> 'Textschlüssel',
	'[[/_admin/builder/source/fixed]]'						=> 'Fester Wert',
	'[[/_admin/builder/source/new-key]]'					=> 'Neuer Schlüssel',
	'[[/_admin/builder/source/new-slot]]'					=> 'Neuer Bildplatz',
	'[[/_admin/builder/source/name]]'						=> 'Name',
	'[[/_admin/builder/source/use]]'						=> 'Verwenden',
	'[[/_admin/builder/source/name-grammar]]'				=> 'Ein Name besteht aus Wörtern in Kleinbuchstaben und Ziffern, mit Bindestrichen verbunden.',
	'[[/_admin/builder/source/name-taken]]'					=> 'Die Section hat diesen Namen schon.',
	'[[/_admin/builder/source/name-slot]]'					=> 'Die Id der Section beginnt mit einer Ziffer, ein Bildplatz muss mit einem Buchstaben beginnen. Benenne die Section um.',
	'[[/_admin/builder/source/name-slot-name]]'				=> 'Der Name eines Bildplatzes muss mit einem Buchstaben beginnen.',
	'[[/_admin/builder/source/no-hits]]'					=> 'Nichts gefunden.',
	'[[/_admin/builder/source/more]]'						=> '%s weitere - grenze die Suche ein.',
	'[[/_admin/builder/source/background]]'					=> 'Hintergrund',
	'[[/_admin/builder/source/focus]]'						=> 'Fokus',
	'[[/_admin/builder/source/remove-background]]'			=> 'Bild entfernen',
	'[[/_admin/builder/source/view-note]]'					=> 'Die Datei, wie sie gespeichert würde. HTML+-Blöcke - die der Builder so lässt, wie sie sind - sind hervorgehoben; hier lässt sich nichts ändern.',

	// Hints under the fields
	'[[/_admin/builder/hint/name]]'							=> 'Eine Zeile. Der Dateiname wird beim Anlegen daraus gebildet und bleibt danach.',
	'[[/_admin/builder/hint/duplicate]]'				=> 'Eine Kopie ist eine eigene Datei mit eigenen Textschlüsseln und Bildplätzen: Sie werden aus denen von %s angelegt, mit denselben Texten und Bildern. Eine Sprache, in der ein Text noch fehlt, bekommt den Text der ersten Sprache.',
	'[[/_admin/builder/hint/template]]'						=> 'Die Datei ist %s. Ihr Name ist die Kategorie der Textschlüssel der Seite, darum ändert er sich nicht.',
	'[[/_admin/builder/hint/id]]'							=> 'Ein Slug, einmal auf der Seite. Er ist der dritte Teil der Schlüssel der Section und der Anker, zu dem die Navigation springt; ein neuer verschiebt die Schlüssel.',
	'[[/_admin/builder/hint/row]]'							=> 'Die Breite des Inhalts in der Section.',
	'[[/_admin/builder/hint/image]]'						=> 'Ein Bild hinter der Section macht sie zu einer Cover- oder Parallax-Section.',
	'[[/_admin/builder/hint/cover]]'						=> 'In Prozent der Fensterhöhe. Leer setzt keine.',
	'[[/_admin/builder/hint/custom]]'						=> 'Klassen aus Nino.css, für die das Formular kein Feld hat, durch Leerzeichen getrennt.',
	'[[/_admin/builder/hint/vpa]]'							=> 'Ob die Animation läuft, wenn die Section ins Bild kommt, und mit welchem Effekt.',
	'[[/_admin/builder/hint/vpa-section]]'				=> 'Wie Template: Die Section trägt genau die Animation des Templates und zieht mit, wo sie sich ändert. Eigene öffnet die Felder dafür.',
	'[[/_admin/builder/hint/vpa-template]]'				=> 'Was eine neue Section bekommt und was eine Section trägt, die auf „wie Template“ steht. Die Seite liest nur die Klassen der Sections.',
	'[[/_admin/builder/hint/time]]'							=> 'Eine css-Zeit wie 200ms oder 1.5s. Leer setzt keine.',
	'[[/_admin/builder/hint/stack-align]]'					=> 'Nur wo es gesetzt ist, legt die Spalte ihre Komponenten als eigenes Raster aus.',
	'[[/_admin/builder/hint/stack-kind]]'					=> 'Statisch ist eine Liste von Komponenten. Ein Loop läuft über die Elemente eines Typs, und was in der Spalte steht, zeigt jede Zelle.',
	'[[/_admin/builder/hint/sort]]'							=> 'Ein Feld des Typs, wie es gespeichert ist.',
	'[[/_admin/builder/hint/limit]]'						=> '0 zeigt alle.',
	'[[/_admin/builder/hint/query]]'						=> 'Feld=Wert-Paare, mit & verbunden, wie der Shortcode elements sie liest. Leer nimmt jedes Element.',
	'[[/_admin/builder/hint/autoheight]]'					=> 'Macht die Zellen des Loops so hoch wie die höchste.',
	'[[/_admin/builder/hint/stack-id]]'						=> 'Woran Filter, gleiche Höhe und Slider den Loop finden. Leer bildet eine aus Section und Typ.',
	'[[/_admin/builder/hint/field]]'						=> 'In einem Loop lesen die Komponenten die Felder jedes Elements.',
	'[[/_admin/builder/hint/field-image]]'					=> 'Ein Feld, das ein Bild enthält.',
	'[[/_admin/builder/hint/fixed]]'						=> 'Der Wert steht im Template: Die Redaktion kann ihn nicht ändern.',
	'[[/_admin/builder/hint/typed]]'						=> 'Du darfst die Schlüssel des Projekts nicht lesen, darum wird ein Schlüssel getippt: /template/<file>/<section>/<name>.',
	'[[/_admin/builder/hint/focus]]'						=> 'Welcher Teil des Bildes beim Zuschneiden bleibt, als eine von neun Positionen.',

	// What the editor asks and says
	'[[/_admin/builder/confirm/rename]]'					=> 'Die Section „%s“ in „%s“ umbenennen? Ihre Textschlüssel und Bildplätze werden beim Speichern des Templates auf den neuen Namen verschoben.',
	'[[/_admin/builder/state/rename]]'						=> 'Section umbenennen',
	'[[/_admin/builder/state/vpa-follow]]'				=> 'Animation des Templates',
	'[[/_admin/builder/state/conflict]]'					=> 'Die Datei hat sich geändert',
	'[[/_admin/builder/state/line]]'						=> 'Zeile %s: %s',
	'[[/_admin/builder/state/narrow]]'						=> 'Ein Template wird am Schreibtisch gebaut: Auf einem so schmalen Bildschirm ist der Editor nur zum Lesen.',
	'[[/_admin/builder/error/id-taken]]'					=> 'Eine andere Section hat diese Id.',
	'[[/_admin/builder/error/id-slug]]'						=> 'Eine Id besteht aus Wörtern in Kleinbuchstaben und Ziffern, mit Bindestrichen verbunden.',
	'[[/_admin/builder/error/red]]'							=> 'Eine Quelle bedeutet dort, wo sie steht, nichts (in der Vorschau rot markiert). Ändere sie zuerst.',
	'[[/_admin/builder/error/source]]'						=> 'Der Quelltext konnte nicht gezeigt werden.',

	// Words of the values of a setting
	'[[/_admin/builder/option/row-default]]'				=> 'Normal',
	'[[/_admin/builder/option/row-narrow]]'					=> 'Schmal',
	'[[/_admin/builder/option/row-wide]]'					=> 'Breit',
	'[[/_admin/builder/option/width-default]]'				=> 'Normal',
	'[[/_admin/builder/option/width-fullwidth]]'			=> 'Volle Breite',
	'[[/_admin/builder/option/width-fullheight]]'			=> 'Volle Höhe',
	'[[/_admin/builder/option/image-cover]]'				=> 'Cover',
	'[[/_admin/builder/option/image-parallax]]'				=> 'Parallax',
	'[[/_admin/builder/option/text-default]]'				=> 'Geerbt',
	'[[/_admin/builder/option/text-left]]'					=> 'Links',
	'[[/_admin/builder/option/text-center]]'				=> 'Mitte',
	'[[/_admin/builder/option/text-right]]'					=> 'Rechts',
	'[[/_admin/builder/option/row-align-default]]'			=> 'Oben',
	'[[/_admin/builder/option/speed-default]]'				=> 'Standard',
	'[[/_admin/builder/option/mode-default]]'				=> 'Einmal',
	'[[/_admin/builder/option/mode-repeat]]'			=> 'Wiederholt',
	'[[/_admin/builder/option/vpa-none]]'					=> 'Keine Animation',
	'[[/_admin/builder/option/vpa-plain]]'					=> 'Standardeffekt',
	'[[/_admin/builder/option/anim-like]]'				=> 'Wie Template',
	'[[/_admin/builder/option/anim-off]]'				=> 'Aus',
	'[[/_admin/builder/option/anim-own]]'				=> 'Eigene',
];
