<?php
declare(strict_types=1);

// The Builder's own workbench strings, one file per interface language (see
// Admin::text()). These are the workbench's, not the site's: they are read
// straight out of this directory while the panel is drawn and are never merged
// into the project. A value is substituted into the page before the shortcode
// pass runs, so none of them carries a bracket.
//
// The parts, by what they hold:
//
//   /_admin/builder/label/...     the buttons, the columns of the list and the names of the editor's regions
//   /_admin/builder/hint/...      the hint under a field of a form
//   /_admin/builder/tree/...      the rows of the tree, what the add rows say, and why a source is red
//   /_admin/builder/menu/...      the menu of a row and the titles of its buttons
//   /_admin/builder/tab/...       the tabs of the forms
//   /_admin/builder/section/...   the fields of the section and row forms
//   /_admin/builder/col/...       the fields of the column form
//   /_admin/builder/stack/...     the fields of the stack form
//   /_admin/builder/component/... the title and the content of the component form
//   /_admin/builder/source/...    the source of a component: its three tabs, the search, a new key or slot
//   /_admin/builder/html/...      the HTML+ editor
//   /_admin/builder/option/...    the words of a value of a setting, as <setting>-<value>; a value with no
//                                 words of its own is shown as it is, and an empty one as "default" or "none"
//   /_admin/builder/state/...     the states the editor is in: a conflict, a rename, the narrow screen
//   /_admin/builder/viewport/...  the three viewports of the preview
//   /_admin/builder/preview/...   what the marks on a frame of the preview mean
//   /_admin/builder/reason/...    why a section is not read, by the code the Reader gives
return [

	'[[/_admin/builder/label/nav]]'						=> 'Builder',

	'[[/_admin/builder/hint/list]]'						=> 'The page templates of the project. The Builder reads each file into sections, columns and components, and writes a file back the way it found it where nothing was changed.',

	'[[/_admin/builder/label/new]]'						=> 'New template',
	'[[/_admin/builder/label/create]]'				=> 'Create',
	'[[/_admin/builder/label/name]]'					=> 'Name',
	'[[/_admin/builder/label/file]]'					=> 'File',
	'[[/_admin/builder/label/header]]'				=> 'Header',
	'[[/_admin/builder/label/footer]]'				=> 'Footer',
	'[[/_admin/builder/label/sections]]'			=> 'Sections',
	'[[/_admin/builder/label/foreign]]'				=> 'HTML+ blocks',
	'[[/_admin/builder/label/readable]]'			=> 'Read completely',
	'[[/_admin/builder/label/used-by]]'				=> 'Used by',
	'[[/_admin/builder/label/none]]'					=> 'none',
	'[[/_admin/builder/label/yes]]'						=> 'Yes',
	'[[/_admin/builder/label/no]]'						=> 'No',
	'[[/_admin/builder/label/open]]'					=> 'Open',
	'[[/_admin/builder/label/delete]]'					=> 'Delete',
	'[[/_admin/builder/label/reload]]'					=> 'Reload',

	'[[/_admin/builder/empty/headline]]'				=> 'No page template yet',
	'[[/_admin/builder/empty/lead]]'						=> 'A page template is a page-*.tpl of the project. Create one here, or write one by hand: the Builder reads it either way.',

	'[[/_admin/builder/msg/deleted]]'					=> 'The template is deleted. Its text keys and image slots stay.',
	'[[/_admin/builder/confirm/delete]]'				=> 'Delete this template? Its text keys and image slots stay.',

	'[[/_admin/builder/error/file]]'					=> 'That is no page template name: page- and then lower case letters, digits and hyphens.',
	'[[/_admin/builder/error/name]]'					=> 'A name is one line of 1 to 160 characters, without angle or square brackets.',
	'[[/_admin/builder/error/header]]'				=> 'The project has no such header template.',
	'[[/_admin/builder/error/footer]]'				=> 'The project has no such footer template.',
	'[[/_admin/builder/error/missing]]'				=> 'There is no such page template.',
	'[[/_admin/builder/error/exists]]'					=> 'A page template of this name is there already.',
	'[[/_admin/builder/error/in-use]]'					=> 'A route renders this template, so it is not deleted. Change the route first.',
	'[[/_admin/builder/error/conflict]]'				=> 'The file changed since it was loaded - in another window, or in the editor of the Templates panel.',
	'[[/_admin/builder/error/invalid]]'				=> 'The template is not valid, and nothing was written.',
	'[[/_admin/builder/error/model]]'					=> 'There was nothing to save.',
	'[[/_admin/builder/error/key]]'						=> 'A text key could not be made or moved.',
	'[[/_admin/builder/error/slot]]'						=> 'An image slot could not be made.',
	'[[/_admin/builder/error/value]]'						=> 'A value holds a quote, a square bracket or a line break, which a shortcode call cannot carry. Nothing was written.',
	'[[/_admin/builder/error/key-exists]]'				=> 'A key or an image slot that a renamed section would take over is there already. Nothing was moved.',
	'[[/_admin/builder/error/permission]]'			=> 'This save makes or moves keys or image slots, and the permission of the panel that owns them is missing.',
	'[[/_admin/builder/error/write]]'					=> 'The file could not be written.',
	'[[/_admin/builder/error/load]]'						=> 'The page templates could not be loaded.',

	'[[/_admin/builder/reason/not-a-section]]'			=> 'A block that is no section',
	'[[/_admin/builder/reason/marker-unclosed]]'		=> 'An HTML+ marker that is never closed',
	'[[/_admin/builder/reason/attribute-syntax]]'		=> 'A tag whose attributes are not written as name="value"',
	'[[/_admin/builder/reason/section-attribute]]'	=> 'The section has the attribute %s, which the Builder does not keep',
	'[[/_admin/builder/reason/section-id]]'				=> 'The section has no id that is a slug',
	'[[/_admin/builder/reason/duplicate-id]]'			=> 'The id %s belongs to an earlier section',
	'[[/_admin/builder/reason/section-class]]'			=> 'The section lacks the class nino-section',
	'[[/_admin/builder/reason/class-token]]'				=> 'The class %s has characters the Builder does not keep',
	'[[/_admin/builder/reason/attribute-value]]'		=> 'The attribute %s has a value the Builder does not keep',
	'[[/_admin/builder/reason/background-class]]'	=> 'The background block has %s, which the Builder does not keep',
	'[[/_admin/builder/reason/background-image]]'	=> 'The background block is not exactly one image call with an empty alt text',
	'[[/_admin/builder/reason/no-row]]'						=> 'The section has no row',
	'[[/_admin/builder/reason/second-row]]'				=> 'The section has more than one row',
	'[[/_admin/builder/reason/section-content]]'		=> 'The section holds markup next to its row',
	'[[/_admin/builder/reason/row-attribute]]'			=> 'The row has the attribute %s, which the Builder does not keep',
	'[[/_admin/builder/reason/row-content]]'				=> 'The row holds something that is no column',
	'[[/_admin/builder/reason/no-cols]]'						=> 'The row has no column',
	'[[/_admin/builder/reason/nested-row]]'				=> 'A row inside a row',
	'[[/_admin/builder/reason/col-attribute]]'			=> 'The column has the attribute %s, which the Builder does not keep',
	'[[/_admin/builder/reason/col-width]]'					=> 'The column has no width class for every viewport',
	'[[/_admin/builder/reason/col-markup]]'				=> 'The column holds markup next to its component calls: %s',
	'[[/_admin/builder/reason/unknown-shortcode]]'	=> 'The shortcode %s is neither a registered component nor a stack',
	'[[/_admin/builder/reason/call-arguments]]'		=> 'A call whose arguments are not written the way the kernel reads them: %s',
	'[[/_admin/builder/reason/unknown-attribute]]'	=> 'The attribute %s is none of the component\'s',
	'[[/_admin/builder/reason/component-content]]'	=> 'The component %s takes no content',
	'[[/_admin/builder/reason/nested-call]]'				=> 'A call inside the content of %s',
	'[[/_admin/builder/reason/stack-source]]'			=> 'A stack without the type it loops',
	'[[/_admin/builder/reason/stack-neighbour]]'		=> 'A stack with other components in its column',
	'[[/_admin/builder/reason/stack-in-stack]]'		=> 'A stack inside a stack',
	'[[/_admin/builder/reason/stack-content]]'			=> 'The stack holds markup next to its component calls: %s',

	// The editor: the two columns, the viewports, the bar
	'[[/_admin/builder/label/tree]]'						=> 'Structure',
	'[[/_admin/builder/label/preview]]'						=> 'Preview',
	'[[/_admin/builder/label/viewports]]'					=> 'Viewport of the preview',
	'[[/_admin/builder/label/source]]'						=> 'Source',
	'[[/_admin/builder/label/open-page]]'					=> 'Open the page',
	'[[/_admin/builder/label/close]]'						=> 'Close',
	'[[/_admin/builder/label/search]]'						=> 'Search templates',
	'[[/_admin/builder/label/no-match]]'					=> 'No template matches.',
	'[[/_admin/builder/label/force]]'						=> 'Save anyway',
	'[[/_admin/builder/viewport/s]]'						=> 'Phone',
	'[[/_admin/builder/viewport/m]]'						=> 'Tablet',
	'[[/_admin/builder/viewport/l]]'						=> 'Desktop',
	'[[/_admin/builder/preview/background]]'				=> 'A picture behind the section',
	'[[/_admin/builder/preview/hidden]]'					=> 'Hidden in this viewport',

	// The tree and its menu
	'[[/_admin/builder/tree/template]]'						=> 'Template',
	'[[/_admin/builder/tree/section]]'						=> 'Section',
	'[[/_admin/builder/tree/html]]'							=> 'HTML+',
	'[[/_admin/builder/tree/html-block]]'					=> 'HTML+ block',
	'[[/_admin/builder/tree/col]]'							=> 'Column',
	'[[/_admin/builder/tree/col-widths]]'					=> 'Widths %s',
	'[[/_admin/builder/tree/stack]]'						=> 'Stack',
	'[[/_admin/builder/tree/component]]'					=> 'Component',
	'[[/_admin/builder/tree/red-static]]'					=> 'A field of an element means nothing in a column without a stack. Choose a text key or a fixed value.',
	'[[/_admin/builder/tree/red-field]]'					=> 'The type of the stack has no such field. Choose another source.',
	'[[/_admin/builder/tree/red-type]]'						=> 'The Elements panel knows no such type. Choose another one.',
	'[[/_admin/builder/menu/settings]]'						=> 'Settings',
	'[[/_admin/builder/menu/template]]'						=> 'Settings of the template',
	'[[/_admin/builder/menu/edit-html]]'					=> 'Edit as HTML+',
	'[[/_admin/builder/menu/cut]]'							=> 'Cut',
	'[[/_admin/builder/menu/paste]]'						=> 'Paste',
	'[[/_admin/builder/menu/duplicate]]'					=> 'Duplicate',
	'[[/_admin/builder/menu/fold]]'							=> 'Fold or unfold',
	'[[/_admin/builder/menu/drag]]'							=> 'Drag to move inside its level',
	'[[/_admin/builder/menu/more]]'							=> 'More',

	// The words of the forms
	'[[/_admin/builder/tab/general]]'						=> 'General',
	'[[/_admin/builder/tab/background]]'					=> 'Background',
	'[[/_admin/builder/tab/spacing]]'						=> 'Spacing',
	'[[/_admin/builder/tab/animation]]'						=> 'Animation',
	'[[/_admin/builder/tab/custom]]'						=> 'Custom',
	'[[/_admin/builder/tab/layout]]'						=> 'Layout',
	'[[/_admin/builder/tab/stack]]'							=> 'Stack',
	'[[/_admin/builder/section/title]]'						=> 'Section "%s"',
	'[[/_admin/builder/section/id]]'						=> 'Id',
	'[[/_admin/builder/section/row]]'						=> 'Row',
	'[[/_admin/builder/section/width]]'						=> 'Section width',
	'[[/_admin/builder/section/color]]'						=> 'Colour',
	'[[/_admin/builder/section/border]]'					=> 'Border',
	'[[/_admin/builder/section/image]]'						=> 'Picture',
	'[[/_admin/builder/section/dim]]'						=> 'Dim the picture',
	'[[/_admin/builder/section/image-pos]]'					=> 'Position of the picture',
	'[[/_admin/builder/section/cover]]'						=> 'Height of the cover',
	'[[/_admin/builder/section/mt]]'						=> 'Margin above',
	'[[/_admin/builder/section/mb]]'						=> 'Margin below',
	'[[/_admin/builder/section/pt]]'						=> 'Padding above',
	'[[/_admin/builder/section/pb]]'						=> 'Padding below',
	'[[/_admin/builder/section/text]]'						=> 'Text alignment',
	'[[/_admin/builder/section/row-align]]'					=> 'Alignment of the columns',
	'[[/_admin/builder/section/custom]]'					=> 'Custom classes',
	'[[/_admin/builder/section/row-custom]]'				=> 'Custom classes of the row',
	'[[/_admin/builder/section/vpa]]'						=> 'Animation',
	'[[/_admin/builder/section/vpa-speed]]'					=> 'Speed',
	'[[/_admin/builder/section/vpa-mode]]'					=> 'Runs',
	'[[/_admin/builder/section/vpa-delay]]'					=> 'Delay',
	'[[/_admin/builder/section/vpa-duration]]'				=> 'Duration',
	'[[/_admin/builder/col/title]]'							=> 'Column of "%s"',
	'[[/_admin/builder/col/width]]'							=> 'Width, %s',
	'[[/_admin/builder/col/hidden]]'						=> 'Hidden, %s',
	'[[/_admin/builder/col/stack-align]]'					=> 'Alignment in the stack',
	'[[/_admin/builder/col/stack-gap]]'						=> 'Gap between the components',
	'[[/_admin/builder/stack/static]]'						=> 'Static',
	'[[/_admin/builder/stack/kind]]'						=> 'Stack',
	'[[/_admin/builder/stack/type]]'						=> 'Type',
	'[[/_admin/builder/stack/type-hint]]'					=> 'The stack takes the types the Elements panel has. A type that is missing is made there first.',
	'[[/_admin/builder/stack/type-missing]]'				=> 'The Elements panel has no such type. Choose one, or make it there first.',
	'[[/_admin/builder/stack/types-link]]'					=> 'Element Types',
	'[[/_admin/builder/stack/sort]]'						=> 'Sort by',
	'[[/_admin/builder/stack/direction]]'					=> 'Direction',
	'[[/_admin/builder/stack/asc]]'							=> 'Ascending',
	'[[/_admin/builder/stack/desc]]'						=> 'Descending',
	'[[/_admin/builder/stack/limit]]'						=> 'Limit',
	'[[/_admin/builder/stack/offset]]'						=> 'Offset',
	'[[/_admin/builder/stack/query]]'						=> 'Query',
	'[[/_admin/builder/stack/cells]]'						=> 'Cell width, %s',
	'[[/_admin/builder/stack/gap]]'							=> 'Gap between the cells',
	'[[/_admin/builder/stack/autoheight]]'					=> 'Cells of equal height',
	'[[/_admin/builder/stack/id]]'							=> 'Id of the stack',
	'[[/_admin/builder/component/title]]'					=> 'Component "%s"',
	'[[/_admin/builder/component/content]]'					=> 'Content',
	'[[/_admin/builder/html/title]]'						=> 'Edit as HTML+',
	'[[/_admin/builder/html/title-new]]'					=> 'New HTML+ block',
	'[[/_admin/builder/html/apply]]'						=> 'Apply',
	'[[/_admin/builder/html/source]]'						=> 'The markup of the block',
	'[[/_admin/builder/html/note]]'							=> 'Anything is allowed here and nothing is made clean. Applying it has the Builder read the block again: if it reads as a section it is one from then on, otherwise it stays as it is.',
	'[[/_admin/builder/html/note-section]]'					=> 'This is the markup the Builder writes for the section. Applying it has the Builder read it again - a section it still reads stays a section.',

	// The source of a component
	'[[/_admin/builder/source/title]]'						=> 'Source',
	'[[/_admin/builder/source/current]]'					=> 'Now:',
	'[[/_admin/builder/source/tab-text]]'					=> 'Text',
	'[[/_admin/builder/source/tab-image]]'					=> 'Image',
	'[[/_admin/builder/source/tab-fixed]]'					=> 'Fixed',
	'[[/_admin/builder/source/key]]'						=> 'Text key',
	'[[/_admin/builder/source/field]]'						=> 'Field of the element',
	'[[/_admin/builder/source/search]]'						=> 'Find a key by its name or its text',
	'[[/_admin/builder/source/search-slot]]'				=> 'Find an image slot',
	'[[/_admin/builder/source/slot]]'						=> 'Image slot',
	'[[/_admin/builder/source/empty-slot]]'					=> 'no picture yet',
	'[[/_admin/builder/source/typed]]'						=> 'Text key',
	'[[/_admin/builder/source/fixed]]'						=> 'Fixed value',
	'[[/_admin/builder/source/new-key]]'					=> 'New key',
	'[[/_admin/builder/source/new-slot]]'					=> 'New image slot',
	'[[/_admin/builder/source/name]]'						=> 'Name',
	'[[/_admin/builder/source/use]]'						=> 'Use it',
	'[[/_admin/builder/source/name-grammar]]'				=> 'A name is lower case words of letters and digits, joined by hyphens.',
	'[[/_admin/builder/source/name-taken]]'					=> 'The section has that name already.',
	'[[/_admin/builder/source/name-slot]]'					=> 'The id of the section starts with a digit, and an image slot has to start with a letter. Rename the section.',
	'[[/_admin/builder/source/name-slot-name]]'				=> 'The name of an image slot has to start with a letter.',
	'[[/_admin/builder/source/no-hits]]'					=> 'Nothing found.',
	'[[/_admin/builder/source/more]]'						=> '%s more - narrow the search.',
	'[[/_admin/builder/source/background]]'					=> 'Background',
	'[[/_admin/builder/source/focus]]'						=> 'Focus',
	'[[/_admin/builder/source/remove-background]]'			=> 'Remove the picture',
	'[[/_admin/builder/source/view-note]]'					=> 'The file as it would be saved. Blocks of HTML+ - the ones the Builder keeps as they are - are marked; nothing can be changed here.',

	// Hints under the fields
	'[[/_admin/builder/hint/name]]'							=> 'One line. The file name is made of it when the template is created and stays as it is.',
	'[[/_admin/builder/hint/template]]'						=> 'The file is %s. Its name is the category of the text keys of the page, so it does not change.',
	'[[/_admin/builder/hint/id]]'							=> 'A slug, once on the page. It is the third part of the keys of the section and the anchor that navigation jumps to; a new one moves the keys.',
	'[[/_admin/builder/hint/row]]'							=> 'The width of the content inside the section.',
	'[[/_admin/builder/hint/image]]'						=> 'A picture behind the section makes it a cover or a parallax section.',
	'[[/_admin/builder/hint/cover]]'						=> 'In percent of the height of the window. Empty sets none.',
	'[[/_admin/builder/hint/custom]]'						=> 'Classes of Nino.css the form has no field for, separated by spaces.',
	'[[/_admin/builder/hint/vpa]]'							=> 'Whether the section is animated when it comes into view, and with which effect.',
	'[[/_admin/builder/hint/time]]'							=> 'A css time such as 200ms or 1.5s. Empty sets none.',
	'[[/_admin/builder/hint/stack-align]]'					=> 'Only where it is set does the column lay its components out as a grid of its own.',
	'[[/_admin/builder/hint/stack-kind]]'					=> 'Static is a list of components. A stack loops the elements of a type, and what is in the column is what each cell shows.',
	'[[/_admin/builder/hint/sort]]'							=> 'A field of the type, as it is stored.',
	'[[/_admin/builder/hint/limit]]'						=> '0 shows all.',
	'[[/_admin/builder/hint/query]]'						=> 'Field=value pairs joined by &, as the elements shortcode reads them. Empty takes every element.',
	'[[/_admin/builder/hint/autoheight]]'					=> 'Makes the cells of the stack as high as the highest.',
	'[[/_admin/builder/hint/stack-id]]'						=> 'What filters, auto height and sliders find the stack by. Empty makes one of the section and the type.',
	'[[/_admin/builder/hint/field]]'						=> 'In a stack the components read the fields of each element.',
	'[[/_admin/builder/hint/field-image]]'					=> 'A field that holds a picture.',
	'[[/_admin/builder/hint/fixed]]'						=> 'The value stands in the template: the editors cannot change it.',
	'[[/_admin/builder/hint/typed]]'						=> 'You may not read the keys of the project, so a key is typed: /template/<file>/<section>/<name>.',
	'[[/_admin/builder/hint/focus]]'						=> 'Which part of the picture survives a crop, as one of nine positions.',

	// What the editor asks and says
	'[[/_admin/builder/confirm/rename]]'					=> 'Rename the section "%s" to "%s"? Its text keys and image slots are moved to the new name when the template is saved.',
	'[[/_admin/builder/state/rename]]'						=> 'Rename the section',
	'[[/_admin/builder/state/conflict]]'					=> 'The file changed',
	'[[/_admin/builder/state/line]]'						=> 'Line %s: %s',
	'[[/_admin/builder/state/narrow]]'						=> 'A template is built at a desk: on a screen this narrow the editor is for reading only.',
	'[[/_admin/builder/error/id-taken]]'					=> 'Another section has that id.',
	'[[/_admin/builder/error/id-slug]]'						=> 'An id is lower case words of letters and digits, joined by hyphens.',
	'[[/_admin/builder/error/red]]'							=> 'A source means nothing where it stands (marked red in the tree). Change it first.',
	'[[/_admin/builder/error/source]]'						=> 'The source could not be shown.',

	// Words of the values of a setting
	'[[/_admin/builder/option/row-default]]'				=> 'Normal',
	'[[/_admin/builder/option/row-narrow]]'					=> 'Narrow',
	'[[/_admin/builder/option/row-wide]]'					=> 'Wide',
	'[[/_admin/builder/option/width-default]]'				=> 'Normal',
	'[[/_admin/builder/option/width-fullwidth]]'			=> 'Full width',
	'[[/_admin/builder/option/width-fullheight]]'			=> 'Full height',
	'[[/_admin/builder/option/image-cover]]'				=> 'Cover',
	'[[/_admin/builder/option/image-parallax]]'				=> 'Parallax',
	'[[/_admin/builder/option/text-default]]'				=> 'Inherited',
	'[[/_admin/builder/option/text-left]]'					=> 'Left',
	'[[/_admin/builder/option/text-center]]'				=> 'Centre',
	'[[/_admin/builder/option/text-right]]'					=> 'Right',
	'[[/_admin/builder/option/row-align-default]]'			=> 'Top',
	'[[/_admin/builder/option/speed-default]]'				=> 'Default',
	'[[/_admin/builder/option/mode-default]]'				=> 'Default',
	'[[/_admin/builder/option/vpa-none]]'					=> 'No animation',
	'[[/_admin/builder/option/vpa-plain]]'					=> 'Default effect',
];
