<?php
declare(strict_types=1);

// The Builder's own workbench strings, one file per interface language (see
// Admin::text()). These are the workbench's, not the site's: they are read
// straight out of this directory while the panel is drawn and are never merged
// into the project. A value is substituted into the page before the shortcode
// pass runs, so none of them carries a bracket.
//
// The parts, by what they hold:
//
//   /_admin/builder/label/...     the buttons, the columns of the list and the names of the editor's regions
//   /_admin/builder/hint/...      the hint under a field of a form
//   /_admin/builder/tree/...      what a frame is called, what the add buttons say, and why a source is red
//   /_admin/builder/menu/...      the titles of the buttons on a frame
//   /_admin/builder/tab/...       the tabs of the forms
//   /_admin/builder/group/...     the headings of the groups of a form
//   /_admin/builder/section/...   the fields of the section and row forms
//   /_admin/builder/template/...  the fields of the template form
//   /_admin/builder/col/...       the fields of the column form
//   /_admin/builder/stack/...     the fields of the loop form (the model and the kernel call it a stack)
//   /_admin/builder/component/... the title and the content of the component form
//   /_admin/builder/source/...    the dialog of a source: its tabs, the search, a new key or slot - and the focus of a picture
//   /_admin/builder/focus/...     the nine places of the focus of a picture
//   /_admin/builder/html/...      the HTML+ editor
//   /_admin/builder/option/...    the words of a value of a setting, as <setting>-<value>; a value with no
//                                 words of its own is shown as it is, and an empty one as "default" or "none"
//   /_admin/builder/state/...     the states the editor is in: a conflict, a rename, the narrow screen
//   /_admin/builder/viewport/...  the viewports of the preview: the three, and all of them at once (g)
//   /_admin/builder/preview/...   what the marks on a frame of the preview mean
//   /_admin/builder/reason/...    why a section is not read, by the code the Reader gives
return [

	'[[/_admin/builder/label/nav]]'						=> 'Builder',

	'[[/_admin/builder/label/new]]'						=> 'New template',
	'[[/_admin/builder/label/create]]'				=> 'Create',
	'[[/_admin/builder/label/name]]'					=> 'Name',
	'[[/_admin/builder/label/file]]'					=> 'File',
	'[[/_admin/builder/label/header]]'				=> 'Header',
	'[[/_admin/builder/label/footer]]'				=> 'Footer',
	'[[/_admin/builder/label/sections]]'			=> 'Sections',
	'[[/_admin/builder/label/used-by]]'				=> 'Used by',
	'[[/_admin/builder/label/none]]'					=> 'none',
	'[[/_admin/builder/label/open]]'					=> 'Open',
	'[[/_admin/builder/label/duplicate]]'				=> 'Duplicate',
	'[[/_admin/builder/label/copy-of]]'					=> 'Copy of %s',
	'[[/_admin/builder/label/delete]]'					=> 'Delete',
	'[[/_admin/builder/label/reload]]'					=> 'Reload',

	'[[/_admin/builder/empty/headline]]'				=> 'No page template yet',
	'[[/_admin/builder/empty/lead]]'						=> 'A page template is a page-*.tpl of the project. Create one here, or write one by hand: the Builder reads it either way.',

	'[[/_admin/builder/msg/deleted]]'					=> 'The template is deleted. Its text keys and image slots stay.',
	'[[/_admin/builder/confirm/delete]]'				=> 'Delete this template? Its text keys and image slots stay.',
	'[[/_admin/builder/confirm/delete-node]]'			=> 'This holds other frames. Delete it together with everything in it?',
	'[[/_admin/builder/confirm/vpa-on]]'					=> 'Should all the sections with no animation of their own follow? Sections affected: %s.',
	'[[/_admin/builder/confirm/vpa-off]]'					=> 'Should all the sections that follow the default go along? Sections affected: %s.',
	'[[/_admin/builder/confirm/vpa-yes]]'				=> 'Change them',
	'[[/_admin/builder/confirm/vpa-no]]'				=> 'Leave them as they are',

	'[[/_admin/builder/error/file]]'					=> 'That is no page template name: page- and then lower case letters, digits and hyphens.',
	'[[/_admin/builder/error/name]]'					=> 'A name is one line of 1 to 160 characters, without angle or square brackets.',
	'[[/_admin/builder/error/header]]'				=> 'The project has no such header template.',
	'[[/_admin/builder/error/footer]]'				=> 'The project has no such footer template.',
	'[[/_admin/builder/error/missing]]'				=> 'There is no such page template.',
	'[[/_admin/builder/error/exists]]'					=> 'A page template of this name is there already.',
	'[[/_admin/builder/error/in-use]]'					=> 'A route renders this template, so it is not deleted. Change the route first.',
	'[[/_admin/builder/error/conflict]]'				=> 'The file changed since it was loaded - in another window, or in another editor.',
	'[[/_admin/builder/error/invalid]]'				=> 'The template is not valid, and nothing was written.',
	'[[/_admin/builder/error/model]]'					=> 'There was nothing to save.',
	'[[/_admin/builder/error/key]]'						=> 'A text key could not be made, copied or moved.',
	'[[/_admin/builder/error/slot]]'						=> 'An image slot could not be made or copied.',
	'[[/_admin/builder/error/value]]'						=> 'A value holds a quote, a square bracket or a line break, which a shortcode call cannot carry. Nothing was written.',
	'[[/_admin/builder/error/key-exists]]'				=> 'A key or an image slot that a renamed section or a copy would make is there already. Nothing was changed.',
	'[[/_admin/builder/error/keys-in-the-way]]'			=> 'Keys in the way: %s.',
	'[[/_admin/builder/error/slots-in-the-way]]'			=> 'Image slots in the way: %s.',
	'[[/_admin/builder/error/permission]]'			=> 'This makes or moves keys or image slots, and the permission of the panel that owns them is missing.',
	'[[/_admin/builder/error/write]]'					=> 'The file could not be written.',
	'[[/_admin/builder/error/load]]'						=> 'The page templates could not be loaded.',

	'[[/_admin/builder/reason/not-a-section]]'			=> 'A block that is no section',
	'[[/_admin/builder/reason/marker-unclosed]]'		=> 'An HTML+ marker that is never closed',
	'[[/_admin/builder/reason/attribute-syntax]]'		=> 'A tag whose attributes are not written as name="value"',
	'[[/_admin/builder/reason/section-attribute]]'	=> 'The section has the attribute %s, which the Builder does not keep',
	'[[/_admin/builder/reason/section-id]]'				=> 'The section has no id that is a slug',
	'[[/_admin/builder/reason/duplicate-id]]'			=> 'The id %s belongs to an earlier section',
	'[[/_admin/builder/reason/section-class]]'			=> 'The section lacks the class nino-section',
	'[[/_admin/builder/reason/class-token]]'				=> 'The class %s has characters the Builder does not keep',
	'[[/_admin/builder/reason/attribute-value]]'		=> 'The attribute %s has a value the Builder does not keep',
	'[[/_admin/builder/reason/background-class]]'	=> 'The background block has %s, which the Builder does not keep',
	'[[/_admin/builder/reason/background-image]]'	=> 'The background block is not exactly one image call with an empty alt text',
	'[[/_admin/builder/reason/no-row]]'						=> 'The section has no row',
	'[[/_admin/builder/reason/second-row]]'				=> 'The section has more than one row',
	'[[/_admin/builder/reason/section-content]]'		=> 'The section holds markup next to its row',
	'[[/_admin/builder/reason/row-attribute]]'			=> 'The row has the attribute %s, which the Builder does not keep',
	'[[/_admin/builder/reason/row-content]]'				=> 'The row holds something that is no column',
	'[[/_admin/builder/reason/no-cols]]'						=> 'The row has no column',
	'[[/_admin/builder/reason/nested-row]]'				=> 'A row inside a row',
	'[[/_admin/builder/reason/col-attribute]]'			=> 'The column has the attribute %s, which the Builder does not keep',
	'[[/_admin/builder/reason/col-width]]'					=> 'The column has no width class for every viewport',
	'[[/_admin/builder/reason/col-markup]]'				=> 'The column holds markup next to its component calls: %s',
	'[[/_admin/builder/reason/unknown-shortcode]]'	=> 'The shortcode %s is neither a registered component nor a loop',
	'[[/_admin/builder/reason/call-arguments]]'		=> 'A call whose arguments are not written the way the kernel reads them: %s',
	'[[/_admin/builder/reason/unknown-attribute]]'	=> 'The attribute %s is none of the component\'s',
	'[[/_admin/builder/reason/component-content]]'	=> 'The component %s takes no content',
	'[[/_admin/builder/reason/nested-call]]'				=> 'A call inside the content of %s',
	'[[/_admin/builder/reason/stack-source]]'			=> 'A loop without the type it loops over',
	'[[/_admin/builder/reason/stack-neighbour]]'		=> 'A loop with other components in its column',
	'[[/_admin/builder/reason/stack-in-stack]]'		=> 'A loop inside a loop',
	'[[/_admin/builder/reason/stack-content]]'			=> 'The loop holds markup next to its component calls: %s',

	// The editor: the preview, the viewports, the bar
	'[[/_admin/builder/label/preview]]'						=> 'Preview',
	'[[/_admin/builder/label/viewports]]'					=> 'Viewport of the preview',
	'[[/_admin/builder/label/source]]'						=> 'Source',
	'[[/_admin/builder/label/open-page]]'					=> 'Open the page',
	'[[/_admin/builder/label/close]]'						=> 'Close',
	'[[/_admin/builder/label/search]]'						=> 'Search templates',
	'[[/_admin/builder/label/no-match]]'					=> 'No template matches.',
	'[[/_admin/builder/label/not-read]]'				=> 'The Builder does not read this file completely.',
	'[[/_admin/builder/label/force]]'						=> 'Save anyway',
	'[[/_admin/builder/viewport/s]]'						=> 'Mobile',
	'[[/_admin/builder/viewport/m]]'						=> 'Tablet',
	'[[/_admin/builder/viewport/l]]'						=> 'Desktop',
	'[[/_admin/builder/viewport/g]]'						=> 'Global',
	'[[/_admin/builder/viewport/all]]'						=> 'All viewports',
	'[[/_admin/builder/preview/background]]'				=> 'A picture behind the section',
	'[[/_admin/builder/preview/hidden]]'					=> 'Hidden in this viewport',
	'[[/_admin/builder/preview/hidden-in]]'					=> 'Hidden in: %s',

	// The frames, what they are called and the buttons on them
	'[[/_admin/builder/tree/template]]'						=> 'Template',
	'[[/_admin/builder/tree/section]]'						=> 'Section',
	'[[/_admin/builder/tree/html-block]]'					=> 'HTML+ block',
	'[[/_admin/builder/tree/col]]'							=> 'Column',
	'[[/_admin/builder/tree/stack]]'						=> 'Element loop',
	'[[/_admin/builder/tree/component]]'					=> 'Component',
	'[[/_admin/builder/tree/red-static]]'					=> 'A field of an element means nothing in a column without a loop. Choose a text key or a fixed value.',
	'[[/_admin/builder/tree/red-field]]'					=> 'The type of the loop has no such field. Choose another source.',
	'[[/_admin/builder/tree/red-type]]'						=> 'The Elements panel knows no such type. Choose another one.',
	'[[/_admin/builder/menu/settings]]'						=> 'Settings',
	'[[/_admin/builder/menu/template]]'						=> 'Settings of the template',
	'[[/_admin/builder/menu/edit-html]]'					=> 'Edit as HTML+',
	'[[/_admin/builder/menu/duplicate]]'					=> 'Duplicate',
	'[[/_admin/builder/menu/tools]]'					=> 'Tools',
	'[[/_admin/builder/menu/rename]]'						=> 'Rename',
	'[[/_admin/builder/menu/loop]]'							=> 'Settings of the loop: %s',

	// The words of the forms
	'[[/_admin/builder/tab/background]]'					=> 'Background',
	'[[/_admin/builder/tab/animation]]'						=> 'Viewport animation',
	'[[/_admin/builder/tab/custom]]'						=> 'CSS classes',
	'[[/_admin/builder/tab/layout]]'						=> 'Layout',
	'[[/_admin/builder/tab/loop]]'							=> 'Loop',
	'[[/_admin/builder/tab/content]]'						=> 'Content',
	'[[/_admin/builder/tab/properties]]'					=> 'Properties',
	'[[/_admin/builder/group/general]]'						=> 'General',
	'[[/_admin/builder/group/frames]]'						=> 'Frames',
	'[[/_admin/builder/group/animation]]'					=> 'Viewport animation',
	'[[/_admin/builder/group/kind]]'						=> 'Kind for this template',
	'[[/_admin/builder/group/data]]'						=> 'Data',
	'[[/_admin/builder/group/order]]'						=> 'Order',
	'[[/_admin/builder/group/grid]]'						=> 'Grid',
	'[[/_admin/builder/group/own]]'							=> 'Own',
	'[[/_admin/builder/section/id]]'						=> 'Id',
	'[[/_admin/builder/section/row]]'						=> 'Row width',
	'[[/_admin/builder/section/fullwidth]]'					=> 'Full width',
	'[[/_admin/builder/section/fullheight]]'				=> 'Full height',
	'[[/_admin/builder/section/color]]'						=> 'Colour',
	'[[/_admin/builder/section/border]]'					=> 'Border',
	'[[/_admin/builder/section/image]]'						=> 'Picture',
	'[[/_admin/builder/section/dim]]'						=> 'Dim the picture',
	'[[/_admin/builder/section/image-pos]]'					=> 'Position of the picture',
	'[[/_admin/builder/section/cover]]'						=> 'Height of the cover',
	'[[/_admin/builder/section/text]]'						=> 'Horizontal alignment',
	'[[/_admin/builder/section/row-align]]'					=> 'Vertical alignment',
	'[[/_admin/builder/section/above]]'					=> 'Above',
	'[[/_admin/builder/section/below]]'					=> 'Below',
	'[[/_admin/builder/section/spacing]]'					=> 'Spacing',
	'[[/_admin/builder/section/spacing-cell]]'				=> '%s, %s',
	'[[/_admin/builder/section/outer]]'					=> 'Margin',
	'[[/_admin/builder/section/inner]]'					=> 'Padding',
	'[[/_admin/builder/section/custom]]'					=> 'Class of the section',
	'[[/_admin/builder/section/row-custom]]'				=> 'Class of the row',
	'[[/_admin/builder/section/vpa]]'						=> 'Animation',
	'[[/_admin/builder/section/vpa-effect]]'			=> 'Effect',
	'[[/_admin/builder/section/vpa-strength]]'				=> 'Strength',
	'[[/_admin/builder/section/vpa-speed]]'					=> 'Speed',
	'[[/_admin/builder/section/vpa-mode]]'					=> 'Repeat',
	'[[/_admin/builder/section/vpa-delay]]'					=> 'Delay',
	'[[/_admin/builder/section/vpa-duration]]'				=> 'Duration',
	'[[/_admin/builder/col/title]]'							=> 'Column of "%s"',
	'[[/_admin/builder/col/width]]'							=> 'Width, %s',
	'[[/_admin/builder/col/hidden]]'						=> 'Hidden, %s',
	'[[/_admin/builder/col/head-device]]'				=> 'Device',
	'[[/_admin/builder/col/head-width]]'				=> 'Width',
	'[[/_admin/builder/col/head-hidden]]'				=> 'Hidden',
	'[[/_admin/builder/col/stack-align]]'					=> 'Alignment of the components',
	'[[/_admin/builder/col/stack-gap]]'						=> 'Gap (--space-*)',
	'[[/_admin/builder/col/custom]]'						=> 'Class of the column',
	'[[/_admin/builder/stack/static]]'						=> 'Static',
	'[[/_admin/builder/stack/kind]]'						=> 'Loop',
	'[[/_admin/builder/stack/type]]'						=> 'Type',
	'[[/_admin/builder/stack/type-hint]]'					=> 'The loop takes the types the Elements panel has. A type that is missing is made there first.',
	'[[/_admin/builder/stack/type-missing]]'				=> 'The Elements panel has no such type. Choose one, or make it there first.',
	'[[/_admin/builder/stack/types-link]]'					=> 'Element Types',
	'[[/_admin/builder/stack/sort]]'						=> 'Sort by',
	'[[/_admin/builder/stack/direction]]'					=> 'Direction',
	'[[/_admin/builder/stack/asc]]'							=> 'Ascending',
	'[[/_admin/builder/stack/desc]]'						=> 'Descending',
	'[[/_admin/builder/stack/limit]]'						=> 'Limit',
	'[[/_admin/builder/stack/offset]]'						=> 'Offset',
	'[[/_admin/builder/stack/query]]'						=> 'Query',
	'[[/_admin/builder/stack/cells]]'						=> 'Cell width, %s',
	'[[/_admin/builder/stack/head-cells]]'					=> 'Cell width',
	'[[/_admin/builder/stack/gap]]'							=> 'Gap between the cells',
	'[[/_admin/builder/stack/autoheight]]'					=> 'Cells of equal height',
	'[[/_admin/builder/stack/id]]'							=> 'Id of the loop',
	'[[/_admin/builder/template/animate]]'					=> 'Animate the sections',
	'[[/_admin/builder/component/title]]'					=> 'Component "%s"',
	'[[/_admin/builder/component/content]]'					=> 'Content',
	'[[/_admin/builder/component/custom]]'					=> 'Class of the component',
	'[[/_admin/builder/html/title]]'						=> 'Edit as HTML+',
	'[[/_admin/builder/html/title-new]]'					=> 'New HTML+ block',
	'[[/_admin/builder/html/apply]]'						=> 'Apply',
	'[[/_admin/builder/html/source]]'						=> 'The markup of the block',
	'[[/_admin/builder/html/note]]'							=> 'Anything is allowed here and nothing is made clean. Applying it has the Builder read the block again: if it reads as a section it is one from then on, otherwise it stays as it is.',
	'[[/_admin/builder/html/note-section]]'					=> 'This is the markup the Builder writes for the section. Applying it has the Builder read it again - a section it still reads stays a section.',

	// The source of a component
	'[[/_admin/builder/source/title]]'						=> 'Source',
	'[[/_admin/builder/source/current]]'					=> 'Current:',
	'[[/_admin/builder/source/current-image]]'				=> 'Current picture:',
	'[[/_admin/builder/source/tab-pick]]'					=> 'Choose a value',
	'[[/_admin/builder/source/tab-new]]'					=> 'Create new',
	'[[/_admin/builder/source/tab-fixed]]'					=> 'Static',
	'[[/_admin/builder/source/key]]'						=> 'Text key',
	'[[/_admin/builder/source/field]]'						=> 'Field of the element',
	'[[/_admin/builder/source/search]]'						=> 'Find a key by its name or its text',
	'[[/_admin/builder/source/search-slot]]'				=> 'Find an image slot',
	'[[/_admin/builder/source/slot]]'						=> 'Image slot',
	'[[/_admin/builder/source/empty-slot]]'					=> 'no picture yet',
	'[[/_admin/builder/source/typed]]'						=> 'Text key',
	'[[/_admin/builder/source/fixed]]'						=> 'Fixed value',
	'[[/_admin/builder/source/new-key]]'					=> 'New key',
	'[[/_admin/builder/source/new-slot]]'					=> 'New image slot',
	'[[/_admin/builder/source/name]]'						=> 'Name',
	'[[/_admin/builder/source/use]]'						=> 'Use it',
	'[[/_admin/builder/source/name-grammar]]'				=> 'A name is lower case words of letters and digits, joined by hyphens.',
	'[[/_admin/builder/source/name-taken]]'					=> 'The section has that name already.',
	'[[/_admin/builder/source/name-slot]]'					=> 'The id of the section starts with a digit, and an image slot has to start with a letter. Rename the section.',
	'[[/_admin/builder/source/name-slot-name]]'				=> 'The name of an image slot has to start with a letter.',
	'[[/_admin/builder/source/no-hits]]'					=> 'Nothing found.',
	'[[/_admin/builder/source/more]]'						=> '%s more - narrow the search.',
	'[[/_admin/builder/source/background]]'					=> 'Background',
	'[[/_admin/builder/source/focus]]'						=> 'Focus',
	'[[/_admin/builder/source/no-focus]]'					=> 'No focus',
	'[[/_admin/builder/source/remove-background]]'			=> 'Remove the picture',
	'[[/_admin/builder/source/view-note]]'					=> 'The file as it would be saved. Blocks of HTML+ - the ones the Builder keeps as they are - are marked; nothing can be changed here.',

	// Hints under the fields
	'[[/_admin/builder/hint/name]]'							=> 'One line. The file name is made of it when the template is created and stays as it is.',
	'[[/_admin/builder/hint/file]]'							=> 'The slug is "%s". The name of the file is the category of the text keys of the page (/template/%s/...), so it does not change.',
	'[[/_admin/builder/hint/animate]]'						=> 'A new section is given the animation, and a section set to like the template carries it. What it looks like is set by the kind below.',
	'[[/_admin/builder/hint/duplicate]]'				=> 'A copy is a file of its own, with text keys and image slots of its own: they are made from the ones of %s, with the same texts and pictures. A language in which a text is still missing gets the text of the first language.',
	'[[/_admin/builder/hint/row]]'							=> 'The width of the content inside the section.',
	'[[/_admin/builder/hint/fullwidth]]'					=> 'The content reaches the left and the right edge.',
	'[[/_admin/builder/hint/fullheight]]'					=> 'The content reaches the top and the bottom of the section.',
	'[[/_admin/builder/hint/image]]'						=> 'A picture behind the section makes it a cover or a parallax section.',
	'[[/_admin/builder/hint/cover]]'						=> 'In percent of the height of the window. Empty sets none.',
	'[[/_admin/builder/hint/custom]]'						=> 'Classes of Nino.css the form has no field for, separated by spaces.',
	'[[/_admin/builder/hint/vpa]]'							=> 'Whether the animation runs when the section comes into view, and with which effect.',
	'[[/_admin/builder/hint/vpa-col]]'						=> 'Whether the animation runs when the column comes into view, and with which effect.',
	'[[/_admin/builder/hint/vpa-section]]'					=> 'Like the template: the section carries the animation the template gives its sections. Off: it is not animated. Own: you set it yourself. Own with the plain effect and nothing else set is Like the template again the next time the dialog is opened.',
	'[[/_admin/builder/hint/vpa-section-off]]'				=> 'The template does not animate its sections, and a section with no animation is like the template. It can have an animation of its own all the same.',
	'[[/_admin/builder/hint/vpa-template]]'					=> 'Handed down to every section below it. With "Default" and "Like the frame" the template sets nothing: then what the frame sets on main or body holds, else Nino.css.',
	'[[/_admin/builder/hint/time]]'							=> 'A css time such as 200ms or 1.5s. Empty sets none.',
	'[[/_admin/builder/hint/stack-align]]'					=> 'Only where it is set does the column lay its components out as a grid of its own.',
	'[[/_admin/builder/hint/stack-kind]]'					=> 'Static is a list of components. A loop runs over the elements of a type, and what is in the column is what each cell shows.',
	'[[/_admin/builder/hint/sort]]'							=> 'A field of the type, as it is stored.',
	'[[/_admin/builder/hint/limit]]'						=> '0 shows all.',
	'[[/_admin/builder/hint/query]]'						=> 'Field=value pairs joined by &, as the elements shortcode reads them. Empty takes every element.',
	'[[/_admin/builder/hint/autoheight]]'					=> 'Makes the cells of the loop as high as the highest.',
	'[[/_admin/builder/hint/stack-id]]'						=> 'What filters, auto height and sliders find the loop by. Empty makes one of the section and the type.',
	'[[/_admin/builder/hint/field]]'						=> 'In a loop the components read the fields of each element.',
	'[[/_admin/builder/hint/field-image]]'					=> 'A field that holds a picture.',
	'[[/_admin/builder/hint/fixed]]'						=> 'The value stands in the template: the editors cannot change it.',
	'[[/_admin/builder/hint/typed]]'						=> 'You may not read the keys of the project, so a key is typed: /template/<file>/<section>/<name>.',
	'[[/_admin/builder/hint/focus]]'						=> 'The part of the picture that stays when it is cropped, as one of nine positions. With no focus it is cropped from the middle.',

	// What the editor asks and says
	'[[/_admin/builder/confirm/rename]]'					=> 'Rename the section "%s" to "%s"? Its text keys and image slots are moved to the new name when the template is saved.',
	'[[/_admin/builder/state/rename]]'						=> 'Rename the section',
	'[[/_admin/builder/state/vpa-follow]]'				=> 'VPA of the template',
	'[[/_admin/builder/state/conflict]]'					=> 'The file changed',
	'[[/_admin/builder/state/line]]'						=> 'Line %s: %s',
	'[[/_admin/builder/state/narrow]]'						=> 'A template is built at a desk: on a screen this narrow the editor is for reading only.',
	'[[/_admin/builder/error/id-taken]]'					=> 'Another section has that id.',
	'[[/_admin/builder/error/id-slug]]'						=> 'An id is lower case words of letters and digits, joined by hyphens.',
	'[[/_admin/builder/error/red]]'							=> 'A source means nothing where it stands (marked red in the preview). Change it first.',
	'[[/_admin/builder/error/source]]'						=> 'The source could not be shown.',

	// Words of the values of a setting
	'[[/_admin/builder/option/row-default]]'				=> 'Normal',
	'[[/_admin/builder/option/row-narrow]]'					=> 'Narrow',
	'[[/_admin/builder/option/row-wide]]'					=> 'Wide',
	'[[/_admin/builder/option/color-default]]'				=> 'Default',
	'[[/_admin/builder/option/color-alt]]'					=> 'Alternate',
	'[[/_admin/builder/option/color-tint]]'					=> 'Tinted',
	'[[/_admin/builder/option/color-dark]]'					=> 'Dark',
	'[[/_admin/builder/option/color-black]]'					=> 'Black',
	'[[/_admin/builder/option/color-primary]]'				=> 'Brand colour',
	'[[/_admin/builder/option/color-brand-alt]]'				=> 'Second colour',
	'[[/_admin/builder/option/border-default]]'				=> 'None',
	'[[/_admin/builder/option/border-1]]'					=> 'Thin',
	'[[/_admin/builder/option/border-2]]'					=> 'Medium',
	'[[/_admin/builder/option/border-3]]'					=> 'Strong',
	'[[/_admin/builder/option/border-primary]]'				=> 'Brand colour',
	'[[/_admin/builder/option/space-default]]'				=> 'Default',
	'[[/_admin/builder/option/image-cover]]'				=> 'Cover',
	'[[/_admin/builder/option/image-parallax]]'				=> 'Parallax',
	'[[/_admin/builder/option/image-default]]'				=> 'None',
	'[[/_admin/builder/option/image-pos-default]]'			=> 'Default',
	'[[/_admin/builder/option/image-pos-top]]'				=> 'Top',
	'[[/_admin/builder/option/image-pos-center]]'				=> 'Centre',
	'[[/_admin/builder/option/image-pos-bottom]]'				=> 'Bottom',
	'[[/_admin/builder/option/text-default]]'				=> 'Inherited',
	'[[/_admin/builder/option/text-left]]'					=> 'Left',
	'[[/_admin/builder/option/text-center]]'				=> 'Centre',
	'[[/_admin/builder/option/text-right]]'					=> 'Right',
	'[[/_admin/builder/option/row-align-default]]'			=> 'Top',
	'[[/_admin/builder/option/row-align-middle]]'			=> 'Middle',
	'[[/_admin/builder/option/row-align-bottom]]'			=> 'Bottom',
	'[[/_admin/builder/option/stack-align-default]]'		=> 'Off',
	'[[/_admin/builder/option/stack-align-start]]'			=> 'Start',
	'[[/_admin/builder/option/stack-align-center]]'			=> 'Centre',
	'[[/_admin/builder/option/stack-align-end]]'			=> 'End',
	'[[/_admin/builder/option/speed-default]]'				=> 'Default',
	'[[/_admin/builder/option/speed-fast]]'					=> 'Fast',
	'[[/_admin/builder/option/speed-medium]]'				=> 'Medium',
	'[[/_admin/builder/option/speed-slow]]'					=> 'Slow',
	'[[/_admin/builder/option/wrap-speed-default]]'			=> 'Like the frame',
	'[[/_admin/builder/option/wrap-speed-fast]]'			=> 'Fast',
	'[[/_admin/builder/option/wrap-speed-medium]]'			=> 'Medium',
	'[[/_admin/builder/option/wrap-speed-slow]]'			=> 'Slow',
	'[[/_admin/builder/option/mode-default]]'				=> 'Once',
	'[[/_admin/builder/option/mode-repeat]]'			=> 'Repeat',
	'[[/_admin/builder/option/vpa-none]]'					=> 'No animation',
	'[[/_admin/builder/option/effect-default]]'				=> 'Default - fade in and rise',
	'[[/_admin/builder/option/effect-zoom]]'				=> 'Zoom',
	'[[/_admin/builder/option/effect-zoom-out]]'			=> 'Zoom out',
	'[[/_admin/builder/option/effect-slide-left]]'			=> 'Slides left',
	'[[/_admin/builder/option/effect-slide-right]]'			=> 'Slides right',
	'[[/_admin/builder/option/effect-flip]]'				=> 'Flip',
	'[[/_admin/builder/option/effect-blur]]'				=> 'Blur',
	'[[/_admin/builder/option/strength-soft]]'				=> 'Soft',
	'[[/_admin/builder/option/strength-medium]]'			=> 'Medium',
	'[[/_admin/builder/option/strength-hard]]'				=> 'Hard',
	'[[/_admin/builder/option/anim-like]]'				=> 'Like the template',
	'[[/_admin/builder/option/anim-like-off]]'				=> 'Like the template (off)',
	'[[/_admin/builder/option/anim-off]]'				=> 'Off',
	'[[/_admin/builder/option/anim-own]]'				=> 'Own',

	// The nine places of the focus of a picture
	'[[/_admin/builder/focus/top-left]]'					=> 'Top left',
	'[[/_admin/builder/focus/top]]'							=> 'Top centre',
	'[[/_admin/builder/focus/top-right]]'					=> 'Top right',
	'[[/_admin/builder/focus/left]]'						=> 'Centre left',
	'[[/_admin/builder/focus/center]]'						=> 'Centre',
	'[[/_admin/builder/focus/right]]'						=> 'Centre right',
	'[[/_admin/builder/focus/bottom-left]]'					=> 'Bottom left',
	'[[/_admin/builder/focus/bottom]]'						=> 'Bottom centre',
	'[[/_admin/builder/focus/bottom-right]]'				=> 'Bottom right',
];
