<?php
// Die Workbench-Texte des Forms-Features, die in seine Fills gemischt
// werden, solange das Feature aktiv ist (siehe text() des Panels) - gleiche
// Schlüssel und Form wie die eigene text/<locale>.php der Workbench. Ein %s
// füllt das Skript, oder das Panel in einer Meldung, die es selbst
// formuliert (siehe sein _say())
return [
	'[[/_admin/nav/forms]]'								=> 'Formulare',
	'[[/_admin/forms/label/forms]]'				=> 'Formulare',

	'[[/_admin/forms/hint/endpoint]]'			=> 'Das Kernel-Modul, das POST /.form beantwortet, ist nicht eingeschaltet - jedes Formular hier würde also ins Leere senden. Trage \\Nino\\Modules\\Form in der config.php wieder unter /nino/modules ein.',
	'[[/_admin/forms/hint/default]]'			=> 'Das ist das Kontaktformular, auf das Nino zurückfällt, solange ein Projekt keines definiert hat - so gezeigt, wie es wäre. Das erste Speichern schreibt /nino/form/forms in die config.php.',
	'[[/_admin/forms/hint/shortcode]]'		=> 'Schreibe %s in ein Template oder einen Text, um dieses Formular auszugeben.',
	'[[/_admin/forms/hint/fields]]'				=> 'Der Name ist das, womit das Feld gesendet und exportiert wird. Ein neues Feld nimmt seinen Namen aus dem Label, bis Du ihn von Hand änderst; ein gespeicherter Name bleibt. Das Label ist das, was ein Besucher liest - ein als Fill geschriebener Textschlüssel wird vor der Ausgabe aufgelöst, ein Label kann also alle Sprachen bedienen, und der Name kommt dann aus dem letzten Teil des Schlüssels. Eine Checkbox passt zu einer Einwilligung: Angehakt sendet sie 1. Diese Namen sind vergeben: %s.',
	'[[/_admin/forms/hint/to]]'						=> 'Leer schickt an die Adresse aus dem Textfill /project/mail/address/owner.',
	'[[/_admin/forms/hint/subject]]'			=> 'Leer nutzt den Textfill /module/form/subject/owner.',
	'[[/_admin/forms/hint/templates]]'		=> 'Die Mail-Templates, die dieses Formular rendert. Ein Feld kommt nur dort in der Mail an, wo sein Template es zeigt: %s zeichnet alle Felder des Formulars, und ein Template, das Du selbst geschrieben hast, kann einzelne Felder benennen. Die Templates eines neuen Projekts tragen es; ein früher installiertes Projekt ergänzt es von Hand.',
	'[[/_admin/forms/hint/retention]]'		=> 'Wie viele Monate an Einsendungen auf der Platte bleiben, 1 bis 60. Ein älterer Monat wird bei der nächsten Einsendung gelöscht - die Mail selbst bleibt davon unberührt.',
	'[[/_admin/forms/hint/store]]'				=> 'Aus heißt: Die Mail geht raus und nichts landet auf der Platte. Das Panel Anfragen bleibt dann absichtlich leer.',

	'[[/_admin/forms/label/new]]'					=> 'Neues Formular',
	'[[/_admin/forms/label/edit]]'				=> 'Bearbeiten',
	'[[/_admin/forms/label/entries]]'			=> '%s gespeichert',
	'[[/_admin/forms/label/delete]]'			=> 'Löschen',
	'[[/_admin/forms/label/form]]'				=> 'Formular',
	'[[/_admin/forms/label/name]]'				=> 'Name',
	'[[/_admin/forms/label/key]]'					=> 'Schlüssel',
	'[[/_admin/forms/label/to]]'					=> 'Senden an',
	'[[/_admin/forms/label/subject]]'			=> 'Betreff',
	'[[/_admin/forms/label/confirm]]'			=> 'Bestätigungsmail an den Besucher',
	'[[/_admin/forms/label/ownertpl]]'		=> 'Template der Betreiber-Mail',
	'[[/_admin/forms/label/usertpl]]'			=> 'Template der Bestätigungsmail',
	'[[/_admin/forms/label/fields]]'			=> 'Felder',
	'[[/_admin/forms/label/fieldname]]'		=> 'Name',
	'[[/_admin/forms/label/fieldlabel]]'	=> 'Label',
	'[[/_admin/forms/label/fieldtype]]'		=> 'Typ',
	'[[/_admin/forms/label/required]]'		=> 'Pflichtfeld',
	'[[/_admin/forms/label/options]]'			=> 'Optionen, eine pro Zeile',
	'[[/_admin/forms/label/addfield]]'		=> 'Feld hinzufügen',
	'[[/_admin/forms/label/removefield]]'	=> 'Entfernen',
	'[[/_admin/forms/label/submissions-settings]]'	=> 'Anfragen',
	'[[/_admin/forms/label/retention]]'		=> 'Aufbewahren (Monate)',
	'[[/_admin/forms/label/store]]'				=> 'Einsendungen speichern',

	'[[/_admin/forms/type/text]]'		=> 'Text',
	'[[/_admin/forms/type/email]]'		=> 'E-Mail-Adresse',
	'[[/_admin/forms/type/tel]]'		=> 'Telefonnummer',
	'[[/_admin/forms/type/url]]'		=> 'Webadresse',
	'[[/_admin/forms/type/number]]'		=> 'Zahl',
	'[[/_admin/forms/type/textarea]]'	=> 'Textfeld',
	'[[/_admin/forms/type/select]]'		=> 'Auswahlliste',
	'[[/_admin/forms/type/checkbox]]'	=> 'Checkbox',
	'[[/_admin/forms/type/radio]]'		=> 'Optionsfelder',
	'[[/_admin/forms/type/date]]'		=> 'Datum',

	'[[/_admin/forms/confirm/delete]]'		=> 'Dieses Formular löschen? Seine Einsendungen bleiben, und das Panel Anfragen zeigt sie weiterhin.',

	'[[/_admin/forms/error/fields]]'		=> 'Das Formular wurde nicht gespeichert. Ändere, was markiert ist, und speichere erneut.',
	'[[/_admin/forms/problem/key]]'			=> 'Der Schlüssel beginnt mit einem Buchstaben und hat nur Kleinbuchstaben, Ziffern und Bindestriche.',
	'[[/_admin/forms/problem/field]]'		=> 'Dieses Feld lässt sich nicht lesen.',
	'[[/_admin/forms/problem/name]]'		=> 'Der Name beginnt mit einem Buchstaben und hat nur Buchstaben, Ziffern, Bindestriche und Unterstriche, höchstens 64 Zeichen.',
	'[[/_admin/forms/problem/reserved]]'	=> 'Das Formular behält diesen Namen für sich. Wähle einen anderen.',
	'[[/_admin/forms/problem/duplicate]]'	=> 'Ein anderes Feld hat diesen Namen schon.',
	'[[/_admin/forms/problem/type]]'		=> 'Diesen Typ gibt es nicht.',
	'[[/_admin/forms/problem/options]]'		=> 'Optionsfelder brauchen mindestens eine Option.',
	'[[/_admin/forms/problem/fields]]'		=> 'Das Formular braucht mindestens ein Feld.',
	'[[/_admin/forms/problem/to]]'			=> 'Das ist keine E-Mail-Adresse.',
	'[[/_admin/forms/problem/ownertpl]]'	=> 'Das ist nicht der Pfad eines Templates. Wähle eines aus der Liste.',
	'[[/_admin/forms/problem/usertpl]]'		=> 'Das ist nicht der Pfad eines Templates. Wähle eines aus der Liste.',
	'[[/_admin/forms/problem/missingtpl]]'	=> 'Ein solches Template gibt es in diesem Projekt nicht. Wähle ein anderes.',
	'[[/_admin/forms/error/invalid]]'		=> 'Das Formular braucht einen eigenen Schlüssel und mindestens ein Feld.',
	'[[/_admin/forms/error/duplicate]]'		=> 'Ein anderes Formular hat diesen Schlüssel bereits.',
	'[[/_admin/forms/error/save]]'			=> 'Die Formulare konnten nicht geschrieben werden.',
	'[[/_admin/forms/error/key]]'			=> 'Kein Formular hat diesen Schlüssel.',
	'[[/_admin/forms/error/last]]'			=> 'Das ist das letzte Formular. Ein Projekt ohne eines fällt auf das eingebaute Kontaktformular zurück; wer gar keines will, schaltet das Form-Modul unter /nino/modules ab.',
	'[[/_admin/forms/error/retention]]'		=> 'Einsendungen werden zwischen 1 und 60 Monaten aufbewahrt.',
];
